# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15b653f6b2cf00d4929ff245b32379c13f3baa109c6d22807c97c821ec90e94198a89075c6208d4554053086aa4d1e4c6201ff325b5b06c65ca012daae1d1b2a

test:
  secret_key_base: 498ab38c2ea3417740ca425c3f2f4fdcefdd3de401f5a5151e802fdb1820756541f453ddc4d248a24f97789c46c78a3c28ff6b907d822d02765fa7119a5e5a89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
